apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secrets
type: Opaque
stringData:
{{- range .Values.databases }}
  {{ .name }}-host: {{ $.Release.Name }}
  {{ .name }}-port: "5432"
  {{ .name }}-db: {{ .name }}
  {{ .name }}-username: {{ .user }}
  {{ .name }}-password: {{ .password }}
  {{ .name }}-jdbc: jdbc:postgresql://{{ $.Release.Name }}:5432/{{ .name }}
{{- end }}