apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-import
  namespace: auth
data:
  realm.json: |
    {
      "realm": "dp-lmwn",
      "enabled": true,
      "verifyEmail": false,
      "registrationEmailAsUsername": false,


      "roles": {
        "realm": [
          { "name": "admin" },
          { "name": "analyst" }
        ]
      },

      "clients": [
        {
          "clientId": "superset",
          "secret": "superset-secret",
          "enabled": true,
          "publicClient": false,
          "redirectUris": ["http://localhost:8088/*"],
          "webOrigins": ["*"]
        }
      ],

      "users": [
        {
          "username": "analyst1",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "test123",
              "temporary": false
            }
          ],
          "realmRoles": ["analyst"]
        },
        {
          "username": "admin",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "admin123",
              "temporary": false
            }
          ],
          "realmRoles": ["admin"]
        }
      ]
    }