apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-import
  namespace: auth
data:
  realm.json: |
    {
      "realm": "dp-lmwn",
      "enabled": true,
      "verifyEmail": false,
      "registrationEmailAsUsername": false,
      "requiredActions": [],

      "roles": {
        "realm": [
          { "name": "admin" },
          { "name": "analyst" },
          { "name": "dashboard_viewer" }
        ]
      },

      "clients": [
        {
          "clientId": "superset",
          "secret": "superset-secret",
          "enabled": true,
          "publicClient": false,
          "redirectUris": ["http://localhost:8088/*"],
          "webOrigins": ["*"],
          "protocolMappers": [
            {
              "name": "realm-roles-as-groups",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-realm-role-mapper",
              "consentRequired": false,
              "config": {
                "multivalued": "true",
                "userinfo.token.claim": "true",
                "id.token.claim": "false",
                "access.token.claim": "false",
                "claim.name": "groups",
                "jsonType.label": "String"
              }
            }
          ]
        }
      ],

      "users": [
        {
          "username": "analyst1",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "analyst1",
              "temporary": false
            }
          ],
          "realmRoles": ["analyst"]
        },
        {
          "username": "admin",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "admin",
              "temporary": false
            }
          ],
          "realmRoles": ["admin"]
        },
        {
          "username": "viewer1",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "viewer1",
              "temporary": false
            }
          ],
          "realmRoles": ["dashboard_viewer"]
        }
      ]
    }