apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  KC_DB_PASSWORD: {{ .Values.database.password | quote }}
  KEYCLOAK_ADMIN: {{ .Values.admin.user | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.admin.password | quote }}
