kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: data-platform
nodes:
  - role: control-plane
    extraPortMappings:
      - { containerPort: 30080, hostPort: 8080, protocol: TCP } # Trino
      - { containerPort: 30088, hostPort: 8088, protocol: TCP } # Superset
      - { containerPort: 30300, hostPort: 3000, protocol: TCP } # Grafana
  - role: worker
  - role: worker
